POST http://localhost:8080/api/create-user
Content-Type: application/json

{
  "name" : "Tadek",
  "age" : "45"
}

###
GET http://localhost:8080/api/test?userName=Jacek

###
GET http://localhost:8080/api/test2


